name: 'Find and replace Action'
description: 'Replaces (sub)strings in files. Useful to enrich configs with previous steps artifacts.'
author: rheuvel89
branding:
  icon: 'repeat'  
  color: 'green'
inputs:
  files:
    description: 'Comma-seperated files list to find and replace in'
    required: true
  source:
    description: 'Source string to be found'
    required: true
  replacement:
    description: 'Replacement string to be replaced with'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
